#!/bin/bash

echo "=== Longitudinal Neuroanalysis Pipeline Structure ==="
echo ""
echo "Project Root:"
tree -I '__pycache__|*.pyc|.git' . 2>/dev/null || find . -type d -not -path './.git*' | sed 's|[^/]*/|  |g'
echo ""
echo "Scripts available in ./src/scripts/:"
echo "  - convert_single_patient.sh  : Convert DICOMs to NIfTI for one patient"
echo "  - convert_all.sh            : Convert DICOMs for all patients"
echo "  - batch_process.sh          : Parallel batch processing"
echo "  - quality_check.sh          : Quality control validation"
echo "  - cleanup.sh                : Clean temporary files"
echo "  - setup_environment.sh      : Environment setup and validation"
echo ""
echo "Usage examples:"
echo "  ./src/scripts/setup_environment.sh"
echo "  ./src/scripts/convert_single_patient.sh data/Patient123"
echo "  ./src/scripts/batch_process.sh -d data/ -j 8"
echo "  ./src/scripts/quality_check.sh"
echo ""
echo "Or use the Makefile:"
echo "  make setup"
echo "  make convert PATIENT=Patient123"
echo "  make batch"
echo "  make qc"
echo ""
